# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command/trail.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='command/trail.proto',
  package='tc.trail',
  serialized_pb='\n\x13\x63ommand/trail.proto\x12\x08tc.trail*%\n\x07\x43ommand\x12\x0c\n\x08REGISTER\x10\x00\x12\x0c\n\x08\x41\x43TIVATE\x10\x03\x42$\n\x1b\x64\x65.walluhn.tc.proto.commandB\x05Trail')

_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='tc.trail.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REGISTER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVATE', index=1, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=33,
  serialized_end=70,
)

Command = enum_type_wrapper.EnumTypeWrapper(_COMMAND)
REGISTER = 0
ACTIVATE = 3




DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\033de.walluhn.tc.proto.commandB\005Trail')
# @@protoc_insertion_point(module_scope)
