# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trail.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import command.trail_pb2
import state.trail_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trail.proto',
  package='tc.trail',
  serialized_pb='\n\x0btrail.proto\x12\x08tc.trail\x1a\x13\x63ommand/trail.proto\x1a\x11state/trail.proto\"\'\n\x05\x45vent\x12\x1e\n\x05state\x18\x01 \x02(\x0e\x32\x0f.tc.trail.State\"+\n\x05Order\x12\"\n\x07\x63ommand\x18\x01 \x02(\x0e\x32\x11.tc.trail.CommandB\x1c\n\x13\x64\x65.walluhn.tc.protoB\x05Trail')




_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='tc.trail.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='tc.trail.Event.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=104,
)


_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='tc.trail.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='tc.trail.Order.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=106,
  serialized_end=149,
)

_EVENT.fields_by_name['state'].enum_type = state.trail_pb2._STATE
_ORDER.fields_by_name['command'].enum_type = command.trail_pb2._COMMAND
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Order'] = _ORDER

class Event(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENT

  # @@protoc_insertion_point(class_scope:tc.trail.Event)

class Order(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORDER

  # @@protoc_insertion_point(class_scope:tc.trail.Order)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\023de.walluhn.tc.protoB\005Trail')
# @@protoc_insertion_point(module_scope)
