# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state/trail.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='state/trail.proto',
  package='tc.trail',
  serialized_pb='\n\x11state/trail.proto\x12\x08tc.trail*7\n\x05State\x12\x08\n\x04IDLE\x10\x00\x12\x0e\n\nREGISTERED\x10\x01\x12\x08\n\x04HOLD\x10\x02\x12\n\n\x06\x41\x43TIVE\x10\x03\x42\"\n\x19\x64\x65.walluhn.tc.proto.stateB\x05Trail')

_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='tc.trail.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTERED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOLD', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=31,
  serialized_end=86,
)

State = enum_type_wrapper.EnumTypeWrapper(_STATE)
IDLE = 0
REGISTERED = 1
HOLD = 2
ACTIVE = 3




DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\031de.walluhn.tc.proto.stateB\005Trail')
# @@protoc_insertion_point(module_scope)
